# Generated by Django 3.2.5 on 2021-07-21 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Public',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=100)),
                ('household_number', models.CharField(max_length=10, unique=True)),
                ('payment', models.DecimalField(decimal_places=3, default=0.0, max_digits=10)),
            ],
            options={
                'db_table': 'publics',
            },
        ),
    ]
