# Generated by Django 3.2.5 on 2021-07-19 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='public',
            name='household_number',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
